name: android-build
on: pull_request
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run domain unit tests
        run: gradle :app:testDebugUnitTest --tests "com.blblblbl.myapplication.domain.*"
      - name: Run presentation unit tests
        run: gradle :app:testDebugUnitTest --tests "com.blblblbl.myapplication.presentation.*"
      - name: Build project
        run: gradle assemble
