name: android-build
on:
  pull_request:
    branches:
      -main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run domain unit tests
        run: ./gradlew :domain:testDebugUnitTest --tests "com.*"
      - name: Run presentation unit tests
        run: ./gradlew :app:testDebugUnitTest --tests "com.*"
      - name: Build project
        run: ./gradlew assemble
