name: android-build
on: pull_request
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run domain unit tests
        working-directory: ./myProject
        run: gradle :app:testDebugUnitTest --tests "com.blblblbl.myapplication.domain.*"
      - name: Run presentation unit tests
        working-directory: ./myProject
        run: gradle :app:testDebugUnitTest --tests "com.blblblbl.myapplication.presentation.*"
      - name: Build project
        working-directory: ./myProject
        run: gradle assembleDebug
